name: new_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  geolocator: ^11.0.0
  http: ^1.2.1
  jiffy: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
